version: '3.8'

services:
    web:
        build: .
        volumes:
            - .:/app
        ports:
            - '8080:8080'
        entrypoint: /app/entrypoint.sh gunicorn
        environment:
            - DB_NAME=kobra_db
            - DB_USER=kobra_user
            - DB_PASSWORD=kobra_password
            - DB_HOST=db
            - DB_PORT=5432
        depends_on:
            db:
                condition: service_healthy
    
    db:
        image: postgres:15
        environment:
            - POSTGRES_DB=kobra_db
            - POSTGRES_USER=kobra_user
            - POSTGRES_PASSWORD=kobra_password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kobra_user -d kobra_db"]
            interval: 3s
            timeout: 3s
            retries: 10

volumes:
    postgres_data:
